baseurl = "/"
languageCode = "en-us"
title = "Lipping Off"
theme = ["hugo-sustain", "reveal-hugo"]
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[menu]
  [[menu.main]]
      name = "blog"
      url = "/blog/"
  
  [[menu.main]]
    name = "talks"
    url = "/talks/"

  [[menu.main]]
    name = "resume"
    url = "/resume.pdf"

[params]
    avatar = "profile.webp"
    author = "Zach Lipp"
    description = "Zach's digital playground"
    custom_css = ["css/custom.css"]
    custom_js = []
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["python", "r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.social]
  Github = "zachlipp"
  Twitter = "zlipp"
  LinkedIn = "zachlipp"

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true
