baseurl = "/"
languageCode = "en-us"
title = "Lipping Off"
theme = "hugo-sustain"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "blog"
    url = "/blog/"
[[menu.main]]
    name = "reading"
    url = "/reading/"
[[menu.main]]
    name = "portfolio"
    url = "/portfolio/"

[params]
    avatar = "profile.jpg"
    author = "Zach"
    description = "Zach's professional website"
    custom_css = ["custom.css"]
    custom_js = []
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["python", "r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.social]
  Github = "zachlipp"
  Twitter = "zlipp"
  LinkedIn = "zachlipp"
