baseurl = "/"
languageCode = "en-us"
title = "Lipping Off"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/zachlipp"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/zlipp"

[params]
    description = "The more serious side of @zlipp"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    themeColor = "theme-zlipp"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
