baseurl = "/"
languageCode = "en-us"
title = "Lipping Off"
theme = ["hugo-sustain", "reveal-hugo"]
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[menu]

  [[menu.main]]
      name = "blog"
      url = "/blog/"

  [[menu.main]]
    name = "talks"
    url = "/talks/"

[params]
    avatar = "lips.png"
    author = "Zach Lipp"
    description = "Zach's digital playground"
    custom_css = ["css/custom.css"]
    slides_css = ["css/slides.css"]
    custom_js = []

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'doom-one'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true

[params.reveal_hugo]
  controls = false
  progress = false
